  export let Students = [
    {
      "id":11,
      "username":"hamzamouddakir",
      "avatar":"https://avatars.githubusercontent.com/u/1?v=4",
      "full_name":"hamza mouddakir",
      "email":"hamzamouddakur@gmail.com",
      "github":"https://github.com/microappstech",
      "description":"hamza mouddakir developper full stack using html and css and javascript and bootsrtrap and sass and tailwind in front end  and c# asp.nety in backend and express.js",
      "phone":"+212637613306",
      "password":"123456789",
      "field":"design"

    },
    {
      "username": "mojombo",
      "id": 1,
      "avatar": "https://avatars.githubusercontent.com/u/1?v=4",
      "full_name": "mahjob reda",
      "email":"mojombo@gmail.com",
      "github": "https://github.com/mojombo",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "defunkt",
      "id": 2,
      "avatar": "https://avatars.githubusercontent.com/u/2?v=4",
      "full_name": "def unket",
      "email":"defunkt@gmail.com",
      "description": "Redwood Tutorial QA Week related items",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "pjhyett",
      "id": 3,
      "email":"hamzamoro@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/3?v=4",
      "full_name": "hamza tech",
      "github": "https://github.com/pjhyett",
      "description": "Redwood Tutorial QA Week related items",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "wycats",
      "id": 4,
      "email":"ahmed@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/4?v=4",
      "full_name": "way the recket",
      "github": "https://github.com/wycats","description": "identify critical items to consider for prioritization and patch release. For Process: https://github.com/redwoodjs/redwood/issues/2067",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "ezmobius",
      "id": 5,
      "avatar": "https://avatars.githubusercontent.com/u/5?v=4",
      "full_name": "hassan red",
      "email":"mojombo@gmail.com",
      "github": "https://github.com/ezmobius","description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "ivey",
      "id": 6,
      "email":"ivey@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/6?v=4",
      "full_name": "ivey rojer",
      "url_github": "https://api.github.com/users/ivey",
      "github": "https://github.com/ivey","description": "PRs must include one \"release:*\" label for categorization",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "evanphx",
      "id": 7,
      "email":"evan@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/7?v=4",
      "full_name": "even code",
      "github": "https://github.com/evanphx",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "vanpelt",
      "id": 17,
      "email":"vanden@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/17?v=4",
      "full_name": "van red",
      "github": "https://github.com/vanpelt",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "wayneeseguin",
      "id": 18,
      "email":"mahmodredo@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/18?v=4",
      "full_name": "mahmod redo",
      "github": "https://github.com/wayneeseguin",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"animation"
    },
    {
      "username": "brynary",
      "id": 19,
      "avatar": "https://avatars.githubusercontent.com/u/19?v=4",
      "full_name": "binary binary",
      "email":"binary@gmail.com",
      "github": "https://github.com/brynary",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "field":"writing"
    },
    {
      "username": "kevinclark",
      "id": 20,
      "avatar": "https://avatars.githubusercontent.com/u/20?v=4",
      "full_name": "keven said",
      "email":"kevensaid@gmail.com",
      "github": "https://github.com/kevinclark",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"animation"
    },
    {
      "username": "technoweenie",
      "id": 21,
      "avatar": "https://avatars.githubusercontent.com/u/21?v=4",
      "full_name": "tech wonie",
      "email":"techwonnie@gmail.com",
      "github": "https://github.com/technoweenie",
      "description": "Redwood Tutorial QA Week related items",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"programming"
    },
    {
      "username": "macournoyer",
      "id": 22,
      "avatar": "https://avatars.githubusercontent.com/u/22?v=4",
      "full_name": "ayoub mackour",
      "email":"maco@gmail.com",
      "github": "https://github.com/macournoyer",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "takeo",
      "id": 23,
      "avatar": "https://avatars.githubusercontent.com/u/23?v=4",
      "full_name": "take care",
      "email":"takeo@gmail.com",
      "github": "https://github.com/takeo",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "caged",
      "id": 25,
      "avatar": "https://avatars.githubusercontent.com/u/25?v=4",
      "full_name": " hamid miro",
      "email":"hamidmiro@gmail.com",
      "github": "https://github.com/caged",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "topfunky",
      "id": 26,
      "email":"ilyasnoufal@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/26?v=4",
      "full_name": "ilyas noufal",
      "url_github": "https://api.github.com/users/topfunky",
      "github": "https://github.com/topfunky",
      "description": "The App Framework for Startups",
      "phone": "+212637916306",
      "password":"123456789",
      "field":"design"
    },
    
    {
      "username": "kevwil",
      "id":27,
      "bio": "amal mona developpeur front end i can make beautifull design and convert any screen to code",
      "avatar": "https://avatars.githubusercontent.com/u/35?v=4",
      "full_name": "amal mona",
      "email":"amalmona@gmail.com",
      "github": "https://github.com/kevwil",
      "description": "The App Framework for Startups",
      "phone": "+217916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "KirinDave",
      "id": 28,
      "email":"zineb@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/36?v=4",
      "full_name": "zineb said",
      "github": "https://github.com/KirinDave",
      "description": "The App Framework for Startups",
      "phone": "+215647916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "jamesgolick",
      "id": 29,
      "email":"jhondari@gmail.com",
      "avatar": "https://avatars.githubusercontent.com/u/37?v=4",
      "full_name": "jhon dari",
      "url_github": "https://api.github.com/users/jamesgolick",
      "github": "https://github.com/jamesgolick",
      "description": "The App Framework for Startups",
      "phone": "+21245916306",
      "password":"123456789",
      "field":"design"
    },
    {
      "username": "atmos",
      "id": 30,
      "bio": "developpeur application mobile front end and backend ",
      "avatar": "https://avatars.githubusercontent.com/u/38?v=4",
      "full_name": "mos maher",
      "email":"mojombo@gmail.com",
      "github": "https://github.com/atmos",
      "description": "The App Framework for Startups",
      "phone": "+212456916306",
      "password":"123456789",
      "field":"design"
    }
  ]
    

